name = "nhachung-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[vars]
ENVIRONMENT = "development"
APP_DOMAIN = "nhachung.org"
APP_ORIGIN = "https://nhachung.org"
API_ORIGIN = "https://api.nhachung.org"
DOCS_ORIGIN = "https://nhachung.org/docs"
COOKIE_SECURE = "true"
FLOW_API_URL = "https://api.flow.muonnoi.org"

[[d1_databases]]
binding = "iai_flow_db"
database_name = "iai-flow-db"
database_id = "73993529-9b2e-42c2-8d40-5b05525ecf4b"

[dev]
port = 8787
